// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkjosjigixkhkgadizqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ram9zamlnaXhraGtnYWRpenFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODQ1ODAsImV4cCI6MjA3MDg2MDU4MH0.wkrq1VBzRX0d93ASH_yVtgtaQFPVKXNYHIc8vpytTEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});